### PR TITLE
CSCMETAX-244: [REF] Use rdflib for fetching and parsing Finto data

### PR DESCRIPTION
**Pull request by osma**
This is the first part of implementing CSCMETAX-244. It doesn't change functionality yet, but replaces the awkward XML parsing of RDF/XML data from Finto with rdflib so that the data is interpreted as RDF triples, which should be more robust since RDF/XML documents can be structured in many different ways and a different structure would break the XML parser.

The downside is that parsing with rdflib is slower. On my PC the execution time for the reference data indexer increased by about 3 minutes.

### CODE REVIEW

**Comment by hannu40k** [comment]
Noting also here that the rdflib-implementation uses a lot more memory, since the http response has to be downloaded entirely, instead of using the previous streaming process. The memory use of ES can probably be toned down through settings to decrease total memory consumption of the dev environment, so the increased memory use should hopefully not be an issue, as it was previously in some cases. Not to mention the benefit of not possibly having the xml-parsing brake in the future if the rdf structure changes.

So as long as metax tests pass, the PR will be merged. (Osma said he will run the tests once back at work)

**Comment by osma** [comment]
I checked the memory usage using /usr/bin/time -v (with GNU time installed):

    Command being timed: "./reindex_all.sh delete_and_reindex"   
    Elapsed (wall clock) time (h:mm:ss or m:ss): 5:08.61
    Maximum resident set size (kbytes): 562044

So yes, this is hardly memory-efficient, but compared to ElasticSearch using over 2GB (of 4GB total) this isn't too bad.

Will check the tests next

**Comment by osma** [comment]
Using `runtests` I got this:

Ran 221 tests in 58.952s
OK

**Comment by hannu40k** [comment]
Testing the PR myself too as soon as I am with a proper internet connection. Sorry for the delay.

**Pull request merged**
